### ISSUE TITLE
Getting names associated with m_iUnitNameIndex

### ISSUE THREAD

**Issue by TodorovicF** [skadistats/clarity-examples#26]
So I'm looking at CDOTA_BaseNPC_Creep_Neutral entities and I'm looking to get the name of the creep, I'm guessing located at the m_iUnitNameIndex of some stringtable. The problem is, I've tried a couple of the stringtable types that make sense (for @OnStringTableEntry("type")), and none of them seem to be giving me the right names. I've tried "EntityNames" and "CombatLogNames" and I'm getting random names for non-creeps. Is there another stringtable I'm missing or a different place to grab the names from? Thanks!

**Comment by spheenik** [comment]
iirc, they all have the same index, which means finding out which one it is is difficult.
Paging @ykim: Can you add something?

**Comment by ykim** [comment]
For both S1 and S2, the neutral's name is not stored inside StringTables.
To obtain it, you're going to have to do some sort of extrapolation to
determine the neutral. It was easy in S1 because you could determine the
neutral creep from the name of its model, but for S2, this method is not
possible as the model name is obscured. I had success in guessing the
neutral type from the properties of the neutral (i.e. hp, mana, abilities,
etc).

**Comment by TodorovicF** [comment]
Thank you for looking into it, I really appreciate it! I've created a mapping based on the neutral's properties as well, figured it was the only other way :)
